services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}